import { db } from '../db/init.js';

// Comprehensive list of 150 careers relevant to Liberia
const careers = [
  // Healthcare & Medicine (20)
  { title: 'Medical Doctor', category: 'Healthcare', description: 'Diagnose and treat illnesses, injuries, and other health conditions. Provide medical care to patients in hospitals, clinics, and private practices.', job_outlook: 'Excellent - High demand', required_education: 'Medical Degree (MD)', salary_range: '$3,000 - $8,000/month', skills_required: 'Medical knowledge, Communication, Problem-solving, Empathy', universities: 'University of Liberia, Cuttington University' },
  { title: 'Nurse', category: 'Healthcare', description: 'Provide patient care, administer medications, and assist doctors in medical procedures. Work in hospitals, clinics, and community health centers.', job_outlook: 'Excellent - High demand', required_education: 'Nursing Diploma or Degree', salary_range: '$800 - $2,500/month', skills_required: 'Patient care, Medical knowledge, Compassion, Attention to detail', universities: 'University of Liberia, Tubman University' },
  { title: 'Pharmacist', category: 'Healthcare', description: 'Dispense medications, provide drug information, and ensure safe medication use. Work in pharmacies, hospitals, and pharmaceutical companies.', job_outlook: 'Very Good', required_education: 'Pharmacy Degree', salary_range: '$1,500 - $4,000/month', skills_required: 'Pharmaceutical knowledge, Attention to detail, Communication', universities: 'University of Liberia' },
  { title: 'Dentist', category: 'Healthcare', description: 'Diagnose and treat oral health problems, perform dental procedures, and promote oral hygiene.', job_outlook: 'Good', required_education: 'Dental Degree (DDS)', salary_range: '$2,000 - $6,000/month', skills_required: 'Dental expertise, Manual dexterity, Patient care', universities: 'University of Liberia' },
  { title: 'Medical Laboratory Technician', category: 'Healthcare', description: 'Perform laboratory tests to help diagnose diseases and monitor patient health.', job_outlook: 'Good', required_education: 'Laboratory Science Diploma', salary_range: '$600 - $1,800/month', skills_required: 'Laboratory skills, Attention to detail, Scientific knowledge', universities: 'University of Liberia' },
  { title: 'Radiologist', category: 'Healthcare', description: 'Use medical imaging to diagnose and treat diseases. Interpret X-rays, CT scans, and MRIs.', job_outlook: 'Very Good', required_education: 'Medical Degree + Specialization', salary_range: '$4,000 - $10,000/month', skills_required: 'Medical imaging, Diagnostic skills, Technical knowledge', universities: 'University of Liberia' },
  { title: 'Physiotherapist', category: 'Healthcare', description: 'Help patients recover from injuries and improve movement through physical therapy.', job_outlook: 'Good', required_education: 'Physiotherapy Degree', salary_range: '$1,000 - $3,000/month', skills_required: 'Physical therapy, Patient care, Communication', universities: 'University of Liberia' },
  { title: 'Public Health Specialist', category: 'Healthcare', description: 'Work to improve community health through education, policy, and disease prevention programs.', job_outlook: 'Very Good', required_education: 'Public Health Degree', salary_range: '$1,200 - $3,500/month', skills_required: 'Public health knowledge, Communication, Planning', universities: 'University of Liberia' },
  { title: 'Midwife', category: 'Healthcare', description: 'Provide care to women during pregnancy, childbirth, and postpartum period.', job_outlook: 'Excellent', required_education: 'Midwifery Diploma or Degree', salary_range: '$800 - $2,200/month', skills_required: 'Maternal care, Communication, Compassion', universities: 'Tubman University' },
  { title: 'Mental Health Counselor', category: 'Healthcare', description: 'Provide counseling and therapy to individuals with mental health issues.', job_outlook: 'Very Good', required_education: 'Psychology or Counseling Degree', salary_range: '$1,000 - $3,000/month', skills_required: 'Counseling skills, Empathy, Communication', universities: 'University of Liberia, Cuttington University' },
  { title: 'Veterinarian', category: 'Healthcare', description: 'Diagnose and treat diseases in animals. Provide veterinary care for pets and livestock.', job_outlook: 'Good', required_education: 'Veterinary Degree', salary_range: '$1,500 - $4,000/month', skills_required: 'Veterinary medicine, Animal care, Problem-solving', universities: 'University of Liberia' },
  { title: 'Optometrist', category: 'Healthcare', description: 'Examine eyes, diagnose vision problems, and prescribe corrective lenses.', job_outlook: 'Good', required_education: 'Optometry Degree', salary_range: '$1,200 - $3,500/month', skills_required: 'Eye care, Diagnostic skills, Patient care', universities: 'University of Liberia' },
  { title: 'Medical Records Administrator', category: 'Healthcare', description: 'Manage patient records and health information systems in healthcare facilities.', job_outlook: 'Good', required_education: 'Health Information Management Degree', salary_range: '$600 - $1,800/month', skills_required: 'Record management, Organization, Computer skills', universities: 'University of Liberia' },
  { title: 'Health Educator', category: 'Healthcare', description: 'Educate communities about health issues and promote healthy behaviors.', job_outlook: 'Good', required_education: 'Health Education Degree', salary_range: '$700 - $2,000/month', skills_required: 'Education, Communication, Public speaking', universities: 'University of Liberia' },
  { title: 'Emergency Medical Technician (EMT)', category: 'Healthcare', description: 'Provide emergency medical care and transport patients to hospitals.', job_outlook: 'Very Good', required_education: 'EMT Certification', salary_range: '$500 - $1,500/month', skills_required: 'Emergency care, Quick thinking, Physical stamina', universities: 'Technical Training Institutes' },
  { title: 'Nutritionist', category: 'Healthcare', description: 'Help people improve their health through proper nutrition and diet planning.', job_outlook: 'Good', required_education: 'Nutrition Degree', salary_range: '$800 - $2,500/month', skills_required: 'Nutrition knowledge, Communication, Planning', universities: 'University of Liberia' },
  { title: 'Medical Social Worker', category: 'Healthcare', description: 'Help patients and families cope with medical conditions and access resources.', job_outlook: 'Good', required_education: 'Social Work Degree', salary_range: '$700 - $2,000/month', skills_required: 'Social work, Empathy, Communication', universities: 'University of Liberia' },
  { title: 'Biomedical Engineer', category: 'Healthcare', description: 'Design and maintain medical equipment and devices used in healthcare.', job_outlook: 'Good', required_education: 'Biomedical Engineering Degree', salary_range: '$1,500 - $4,000/month', skills_required: 'Engineering, Medical knowledge, Problem-solving', universities: 'University of Liberia' },
  { title: 'Health Inspector', category: 'Healthcare', description: 'Inspect facilities to ensure compliance with health and safety regulations.', job_outlook: 'Good', required_education: 'Public Health or Environmental Health Degree', salary_range: '$800 - $2,200/month', skills_required: 'Inspection skills, Knowledge of regulations, Attention to detail', universities: 'University of Liberia' },
  { title: 'Medical Researcher', category: 'Healthcare', description: 'Conduct research to advance medical knowledge and develop new treatments.', job_outlook: 'Good', required_education: 'Medical or Research Degree', salary_range: '$1,200 - $3,500/month', skills_required: 'Research skills, Scientific knowledge, Analysis', universities: 'University of Liberia' },

  // Education (15)
  { title: 'Primary School Teacher', category: 'Education', description: 'Teach children in grades 1-6, covering basic subjects like reading, math, and science.', job_outlook: 'Excellent - High demand', required_education: 'Teaching Certificate or Degree', salary_range: '$400 - $1,200/month', skills_required: 'Teaching, Patience, Communication, Creativity', universities: 'University of Liberia, Cuttington University, Teacher Training Colleges' },
  { title: 'Secondary School Teacher', category: 'Education', description: 'Teach students in grades 7-12 in specific subject areas like math, science, or English.', job_outlook: 'Excellent - High demand', required_education: 'Teaching Degree in Subject Area', salary_range: '$500 - $1,500/month', skills_required: 'Subject expertise, Teaching, Communication', universities: 'University of Liberia, Cuttington University' },
  { title: 'University Professor', category: 'Education', description: 'Teach college students, conduct research, and publish academic work.', job_outlook: 'Good', required_education: 'Master\'s or PhD Degree', salary_range: '$1,500 - $4,000/month', skills_required: 'Subject expertise, Research, Teaching', universities: 'University of Liberia, Cuttington University' },
  { title: 'School Principal', category: 'Education', description: 'Manage school operations, oversee teachers, and ensure quality education.', job_outlook: 'Good', required_education: 'Education Degree + Leadership Training', salary_range: '$1,200 - $3,000/month', skills_required: 'Leadership, Management, Education knowledge', universities: 'University of Liberia' },
  { title: 'Education Administrator', category: 'Education', description: 'Manage educational programs and policies at district or national level.', job_outlook: 'Good', required_education: 'Education or Public Administration Degree', salary_range: '$1,000 - $2,800/month', skills_required: 'Administration, Policy knowledge, Leadership', universities: 'University of Liberia' },
  { title: 'Special Education Teacher', category: 'Education', description: 'Work with students who have special needs or learning disabilities.', job_outlook: 'Very Good', required_education: 'Special Education Degree', salary_range: '$600 - $1,800/month', skills_required: 'Special education, Patience, Empathy', universities: 'University of Liberia' },
  { title: 'Guidance Counselor', category: 'Education', description: 'Help students with academic planning, career choices, and personal issues.', job_outlook: 'Very Good', required_education: 'Counseling or Psychology Degree', salary_range: '$700 - $2,000/month', skills_required: 'Counseling, Communication, Empathy', universities: 'University of Liberia, Cuttington University' },
  { title: 'Librarian', category: 'Education', description: 'Manage library resources and help students and researchers find information.', job_outlook: 'Good', required_education: 'Library Science Degree', salary_range: '$500 - $1,500/month', skills_required: 'Information management, Organization, Communication', universities: 'University of Liberia' },
  { title: 'Curriculum Developer', category: 'Education', description: 'Design educational curricula and learning materials for schools.', job_outlook: 'Good', required_education: 'Education Degree', salary_range: '$800 - $2,200/month', skills_required: 'Curriculum design, Education knowledge, Writing', universities: 'University of Liberia' },
  { title: 'Adult Education Instructor', category: 'Education', description: 'Teach adults basic literacy, vocational skills, or continuing education courses.', job_outlook: 'Good', required_education: 'Teaching Certificate or Degree', salary_range: '$500 - $1,500/month', skills_required: 'Teaching, Patience, Communication', universities: 'Teacher Training Colleges' },
  { title: 'Early Childhood Educator', category: 'Education', description: 'Work with young children (ages 0-5) to develop basic skills and prepare for school.', job_outlook: 'Very Good', required_education: 'Early Childhood Education Certificate', salary_range: '$400 - $1,200/month', skills_required: 'Child development, Patience, Creativity', universities: 'Teacher Training Colleges' },
  { title: 'Educational Technology Specialist', category: 'Education', description: 'Integrate technology into education and train teachers on educational tools.', job_outlook: 'Very Good', required_education: 'Education Technology Degree', salary_range: '$800 - $2,500/month', skills_required: 'Technology, Education, Training', universities: 'University of Liberia' },
  { title: 'School Psychologist', category: 'Education', description: 'Assess and support students\' mental health and learning needs.', job_outlook: 'Good', required_education: 'Psychology Degree', salary_range: '$1,000 - $2,800/month', skills_required: 'Psychology, Assessment, Communication', universities: 'University of Liberia' },
  { title: 'Vocational Trainer', category: 'Education', description: 'Teach practical skills like carpentry, tailoring, or mechanics.', job_outlook: 'Very Good', required_education: 'Vocational Training Certificate', salary_range: '$600 - $1,800/month', skills_required: 'Practical skills, Teaching, Communication', universities: 'Vocational Training Institutes' },
  { title: 'Education Researcher', category: 'Education', description: 'Conduct research to improve educational methods and policies.', job_outlook: 'Good', required_education: 'Education or Research Degree', salary_range: '$1,000 - $2,800/month', skills_required: 'Research, Analysis, Education knowledge', universities: 'University of Liberia' },

  // Engineering & Technology (20)
  { title: 'Civil Engineer', category: 'Engineering', description: 'Design and oversee construction of infrastructure like roads, bridges, and buildings.', job_outlook: 'Excellent', required_education: 'Civil Engineering Degree', salary_range: '$1,500 - $4,500/month', skills_required: 'Engineering, Design, Project management', universities: 'University of Liberia' },
  { title: 'Electrical Engineer', category: 'Engineering', description: 'Design and maintain electrical systems, power grids, and electronic devices.', job_outlook: 'Very Good', required_education: 'Electrical Engineering Degree', salary_range: '$1,500 - $4,500/month', skills_required: 'Electrical systems, Problem-solving, Technical skills', universities: 'University of Liberia' },
  { title: 'Mechanical Engineer', category: 'Engineering', description: 'Design and maintain mechanical systems, machinery, and equipment.', job_outlook: 'Very Good', required_education: 'Mechanical Engineering Degree', salary_range: '$1,500 - $4,500/month', skills_required: 'Mechanical systems, Design, Problem-solving', universities: 'University of Liberia' },
  { title: 'Software Developer', category: 'Technology', description: 'Design and develop computer software and applications.', job_outlook: 'Excellent', required_education: 'Computer Science or Software Engineering Degree', salary_range: '$1,200 - $4,000/month', skills_required: 'Programming, Problem-solving, Creativity', universities: 'University of Liberia' },
  { title: 'Computer Programmer', category: 'Technology', description: 'Write code to create software programs and applications.', job_outlook: 'Excellent', required_education: 'Computer Science Degree or Certification', salary_range: '$1,000 - $3,500/month', skills_required: 'Programming languages, Logic, Problem-solving', universities: 'University of Liberia' },
  { title: 'Network Administrator', category: 'Technology', description: 'Manage and maintain computer networks and IT infrastructure.', job_outlook: 'Very Good', required_education: 'IT or Network Administration Degree', salary_range: '$1,000 - $3,000/month', skills_required: 'Networking, Troubleshooting, Technical skills', universities: 'University of Liberia' },
  { title: 'Database Administrator', category: 'Technology', description: 'Manage and maintain databases to store and organize information.', job_outlook: 'Very Good', required_education: 'IT or Database Management Degree', salary_range: '$1,200 - $3,500/month', skills_required: 'Database management, SQL, Problem-solving', universities: 'University of Liberia' },
  { title: 'Web Developer', category: 'Technology', description: 'Design and build websites and web applications.', job_outlook: 'Excellent', required_education: 'Web Development Degree or Certification', salary_range: '$800 - $3,000/month', skills_required: 'Web technologies, Design, Programming', universities: 'University of Liberia' },
  { title: 'IT Support Specialist', category: 'Technology', description: 'Help users with computer problems and maintain IT systems.', job_outlook: 'Very Good', required_education: 'IT Degree or Certification', salary_range: '$600 - $2,000/month', skills_required: 'Troubleshooting, Communication, Technical knowledge', universities: 'University of Liberia, Technical Institutes' },
  { title: 'Cybersecurity Specialist', category: 'Technology', description: 'Protect computer systems and networks from cyber threats.', job_outlook: 'Excellent', required_education: 'Cybersecurity or IT Degree', salary_range: '$1,500 - $4,500/month', skills_required: 'Security, Networking, Problem-solving', universities: 'University of Liberia' },
  { title: 'Telecommunications Engineer', category: 'Engineering', description: 'Design and maintain communication systems and networks.', job_outlook: 'Very Good', required_education: 'Telecommunications or Electrical Engineering Degree', salary_range: '$1,500 - $4,000/month', skills_required: 'Telecommunications, Engineering, Problem-solving', universities: 'University of Liberia' },
  { title: 'Systems Analyst', category: 'Technology', description: 'Analyze business needs and design IT solutions.', job_outlook: 'Very Good', required_education: 'IT or Business Degree', salary_range: '$1,200 - $3,500/month', skills_required: 'Analysis, Business knowledge, Technical skills', universities: 'University of Liberia' },
  { title: 'Mobile App Developer', category: 'Technology', description: 'Create mobile applications for smartphones and tablets.', job_outlook: 'Excellent', required_education: 'Computer Science or Mobile Development Degree', salary_range: '$1,200 - $4,000/month', skills_required: 'Mobile development, Programming, Design', universities: 'University of Liberia' },
  { title: 'Data Analyst', category: 'Technology', description: 'Analyze data to help organizations make informed decisions.', job_outlook: 'Excellent', required_education: 'Data Science, Statistics, or IT Degree', salary_range: '$1,200 - $3,500/month', skills_required: 'Data analysis, Statistics, Problem-solving', universities: 'University of Liberia' },
  { title: 'Cloud Computing Specialist', category: 'Technology', description: 'Manage cloud-based IT infrastructure and services.', job_outlook: 'Excellent', required_education: 'IT or Cloud Computing Degree', salary_range: '$1,500 - $4,500/month', skills_required: 'Cloud platforms, Networking, Security', universities: 'University of Liberia' },
  { title: 'IT Project Manager', category: 'Technology', description: 'Oversee IT projects from planning to completion.', job_outlook: 'Very Good', required_education: 'IT or Project Management Degree', salary_range: '$1,500 - $4,000/month', skills_required: 'Project management, Leadership, Technical knowledge', universities: 'University of Liberia' },
  { title: 'Computer Hardware Engineer', category: 'Engineering', description: 'Design and develop computer hardware components.', job_outlook: 'Good', required_education: 'Computer Engineering or Electrical Engineering Degree', salary_range: '$1,500 - $4,000/month', skills_required: 'Hardware design, Engineering, Problem-solving', universities: 'University of Liberia' },
  { title: 'UI/UX Designer', category: 'Technology', description: 'Design user interfaces and experiences for software and websites.', job_outlook: 'Very Good', required_education: 'Design or IT Degree', salary_range: '$1,000 - $3,500/month', skills_required: 'Design, Creativity, User research', universities: 'University of Liberia' },
  { title: 'IT Consultant', category: 'Technology', description: 'Provide expert advice on IT strategies and solutions to businesses.', job_outlook: 'Very Good', required_education: 'IT Degree + Experience', salary_range: '$1,500 - $5,000/month', skills_required: 'IT expertise, Consulting, Communication', universities: 'University of Liberia' },
  { title: 'Robotics Engineer', category: 'Engineering', description: 'Design and build robots and automated systems.', job_outlook: 'Good', required_education: 'Robotics or Mechanical Engineering Degree', salary_range: '$1,800 - $5,000/month', skills_required: 'Robotics, Programming, Engineering', universities: 'University of Liberia' },

  // Business & Finance (20)
  { title: 'Accountant', category: 'Business', description: 'Manage financial records, prepare tax returns, and analyze financial data.', job_outlook: 'Excellent', required_education: 'Accounting Degree', salary_range: '$800 - $2,500/month', skills_required: 'Accounting, Math, Attention to detail', universities: 'University of Liberia, Cuttington University' },
  { title: 'Financial Analyst', category: 'Business', description: 'Analyze financial data to help businesses make investment decisions.', job_outlook: 'Very Good', required_education: 'Finance or Accounting Degree', salary_range: '$1,200 - $3,500/month', skills_required: 'Financial analysis, Math, Critical thinking', universities: 'University of Liberia' },
  { title: 'Business Manager', category: 'Business', description: 'Oversee business operations and manage teams to achieve goals.', job_outlook: 'Very Good', required_education: 'Business Administration Degree', salary_range: '$1,200 - $4,000/month', skills_required: 'Management, Leadership, Business knowledge', universities: 'University of Liberia, Cuttington University' },
  { title: 'Entrepreneur', category: 'Business', description: 'Start and run your own business venture.', job_outlook: 'Good', required_education: 'Business knowledge + Experience', salary_range: 'Variable - Depends on business success', skills_required: 'Business skills, Risk-taking, Innovation', universities: 'University of Liberia, Business Schools' },
  { title: 'Marketing Manager', category: 'Business', description: 'Develop marketing strategies to promote products and services.', job_outlook: 'Very Good', required_education: 'Marketing or Business Degree', salary_range: '$1,000 - $3,500/month', skills_required: 'Marketing, Creativity, Communication', universities: 'University of Liberia' },
  { title: 'Sales Representative', category: 'Business', description: 'Sell products or services to customers and build client relationships.', job_outlook: 'Very Good', required_education: 'High School + Sales Training', salary_range: '$500 - $2,000/month + Commission', skills_required: 'Sales, Communication, Persistence', universities: 'On-the-job training' },
  { title: 'Human Resources Manager', category: 'Business', description: 'Manage employee recruitment, training, and workplace policies.', job_outlook: 'Very Good', required_education: 'HR or Business Degree', salary_range: '$1,000 - $3,000/month', skills_required: 'HR knowledge, Communication, Problem-solving', universities: 'University of Liberia' },
  { title: 'Banker', category: 'Business', description: 'Help customers with banking services like loans, accounts, and investments.', job_outlook: 'Very Good', required_education: 'Finance or Business Degree', salary_range: '$800 - $2,500/month', skills_required: 'Banking, Customer service, Math', universities: 'University of Liberia' },
  { title: 'Insurance Agent', category: 'Business', description: 'Sell insurance policies and help clients with claims.', job_outlook: 'Good', required_education: 'High School + Insurance License', salary_range: '$600 - $2,000/month + Commission', skills_required: 'Sales, Communication, Insurance knowledge', universities: 'Insurance Training Programs' },
  { title: 'Real Estate Agent', category: 'Business', description: 'Help clients buy, sell, or rent properties.', job_outlook: 'Good', required_education: 'High School + Real Estate License', salary_range: 'Commission-based', skills_required: 'Sales, Negotiation, Market knowledge', universities: 'Real Estate Training Programs' },
  { title: 'Supply Chain Manager', category: 'Business', description: 'Manage the flow of goods from suppliers to customers.', job_outlook: 'Very Good', required_education: 'Supply Chain or Business Degree', salary_range: '$1,200 - $3,500/month', skills_required: 'Logistics, Planning, Problem-solving', universities: 'University of Liberia' },
  { title: 'Operations Manager', category: 'Business', description: 'Oversee daily business operations and improve efficiency.', job_outlook: 'Very Good', required_education: 'Business Administration Degree', salary_range: '$1,200 - $3,500/month', skills_required: 'Operations, Management, Problem-solving', universities: 'University of Liberia' },
  { title: 'Business Consultant', category: 'Business', description: 'Provide expert advice to help businesses improve performance.', job_outlook: 'Good', required_education: 'Business Degree + Experience', salary_range: '$1,500 - $5,000/month', skills_required: 'Business expertise, Analysis, Communication', universities: 'University of Liberia' },
  { title: 'Auditor', category: 'Business', description: 'Examine financial records to ensure accuracy and compliance.', job_outlook: 'Very Good', required_education: 'Accounting Degree', salary_range: '$1,000 - $3,000/month', skills_required: 'Accounting, Attention to detail, Analysis', universities: 'University of Liberia' },
  { title: 'Tax Advisor', category: 'Business', description: 'Help individuals and businesses with tax planning and preparation.', job_outlook: 'Very Good', required_education: 'Accounting or Tax Degree', salary_range: '$1,000 - $3,000/month', skills_required: 'Tax knowledge, Math, Communication', universities: 'University of Liberia' },
  { title: 'Investment Advisor', category: 'Business', description: 'Help clients make investment decisions and manage portfolios.', job_outlook: 'Good', required_education: 'Finance Degree + Certification', salary_range: '$1,200 - $4,000/month', skills_required: 'Finance, Analysis, Communication', universities: 'University of Liberia' },
  { title: 'Retail Manager', category: 'Business', description: 'Manage retail stores and oversee sales staff.', job_outlook: 'Good', required_education: 'Business Degree or Experience', salary_range: '$700 - $2,000/month', skills_required: 'Management, Customer service, Sales', universities: 'University of Liberia' },
  { title: 'Event Planner', category: 'Business', description: 'Organize and coordinate events like weddings, conferences, and parties.', job_outlook: 'Good', required_education: 'Event Management or Business Degree', salary_range: '$600 - $2,500/month', skills_required: 'Planning, Organization, Communication', universities: 'University of Liberia' },
  { title: 'Public Relations Specialist', category: 'Business', description: 'Manage company image and communicate with the public and media.', job_outlook: 'Good', required_education: 'PR or Communications Degree', salary_range: '$800 - $2,500/month', skills_required: 'Communication, Writing, Media relations', universities: 'University of Liberia' },
  { title: 'Customer Service Representative', category: 'Business', description: 'Help customers with questions, complaints, and service requests.', job_outlook: 'Very Good', required_education: 'High School + Training', salary_range: '$400 - $1,200/month', skills_required: 'Customer service, Communication, Patience', universities: 'On-the-job training' },

  // Agriculture & Environment (15)
  { title: 'Agricultural Engineer', category: 'Agriculture', description: 'Design farming equipment and systems to improve agricultural productivity.', job_outlook: 'Very Good', required_education: 'Agricultural Engineering Degree', salary_range: '$1,200 - $3,500/month', skills_required: 'Engineering, Agriculture, Problem-solving', universities: 'University of Liberia' },
  { title: 'Agronomist', category: 'Agriculture', description: 'Study crops and soil to improve farming methods and yields.', job_outlook: 'Very Good', required_education: 'Agriculture or Agronomy Degree', salary_range: '$1,000 - $3,000/month', skills_required: 'Agriculture, Science, Research', universities: 'University of Liberia' },
  { title: 'Farm Manager', category: 'Agriculture', description: 'Oversee farm operations and manage agricultural production.', job_outlook: 'Very Good', required_education: 'Agriculture Degree or Experience', salary_range: '$800 - $2,500/month', skills_required: 'Farming, Management, Planning', universities: 'University of Liberia' },
  { title: 'Veterinary Technician', category: 'Agriculture', description: 'Assist veterinarians in caring for animals.', job_outlook: 'Good', required_education: 'Veterinary Technology Diploma', salary_range: '$600 - $1,800/month', skills_required: 'Animal care, Medical knowledge, Compassion', universities: 'Technical Institutes' },
  { title: 'Forestry Specialist', category: 'Agriculture', description: 'Manage forests and promote sustainable forestry practices.', job_outlook: 'Good', required_education: 'Forestry Degree', salary_range: '$1,000 - $2,800/month', skills_required: 'Forestry, Environmental knowledge, Planning', universities: 'University of Liberia' },
  { title: 'Environmental Scientist', category: 'Agriculture', description: 'Study the environment and develop solutions to environmental problems.', job_outlook: 'Very Good', required_education: 'Environmental Science Degree', salary_range: '$1,200 - $3,500/month', skills_required: 'Science, Research, Problem-solving', universities: 'University of Liberia' },
  { title: 'Fisheries Manager', category: 'Agriculture', description: 'Manage fish farms and sustainable fishing practices.', job_outlook: 'Good', required_education: 'Fisheries or Marine Science Degree', salary_range: '$1,000 - $3,000/month', skills_required: 'Fisheries, Management, Environmental knowledge', universities: 'University of Liberia' },
  { title: 'Soil Scientist', category: 'Agriculture', description: 'Study soil composition to improve agricultural productivity.', job_outlook: 'Good', required_education: 'Soil Science or Agriculture Degree', salary_range: '$1,000 - $3,000/month', skills_required: 'Science, Research, Agriculture', universities: 'University of Liberia' },
  { title: 'Agricultural Extension Officer', category: 'Agriculture', description: 'Educate farmers about new techniques and technologies.', job_outlook: 'Very Good', required_education: 'Agriculture Degree', salary_range: '$800 - $2,200/month', skills_required: 'Agriculture, Education, Communication', universities: 'University of Liberia' },
  { title: 'Livestock Manager', category: 'Agriculture', description: 'Manage livestock operations including cattle, goats, and poultry.', job_outlook: 'Very Good', required_education: 'Animal Science or Agriculture Degree', salary_range: '$800 - $2,500/month', skills_required: 'Animal care, Management, Planning', universities: 'University of Liberia' },
  { title: 'Food Scientist', category: 'Agriculture', description: 'Develop and improve food products and ensure food safety.', job_outlook: 'Good', required_education: 'Food Science Degree', salary_range: '$1,200 - $3,500/month', skills_required: 'Science, Food knowledge, Research', universities: 'University of Liberia' },
  { title: 'Agricultural Economist', category: 'Agriculture', description: 'Analyze economic factors affecting agriculture and food systems.', job_outlook: 'Good', required_education: 'Agricultural Economics Degree', salary_range: '$1,200 - $3,500/month', skills_required: 'Economics, Agriculture, Analysis', universities: 'University of Liberia' },
  { title: 'Conservation Officer', category: 'Agriculture', description: 'Protect natural resources and wildlife habitats.', job_outlook: 'Good', required_education: 'Environmental Science or Conservation Degree', salary_range: '$800 - $2,500/month', skills_required: 'Conservation, Environmental knowledge, Communication', universities: 'University of Liberia' },
  { title: 'Beekeeper', category: 'Agriculture', description: 'Manage beehives and produce honey and other bee products.', job_outlook: 'Good', required_education: 'Beekeeping Training', salary_range: '$600 - $2,000/month', skills_required: 'Beekeeping, Animal care, Business skills', universities: 'Vocational Training' },
  { title: 'Organic Farmer', category: 'Agriculture', description: 'Grow crops using organic and sustainable farming methods.', job_outlook: 'Good', required_education: 'Agriculture Training or Experience', salary_range: 'Variable - Depends on farm size', skills_required: 'Farming, Sustainability, Business skills', universities: 'Agricultural Training Programs' },

  // Law & Legal (10)
  { title: 'Lawyer', category: 'Law', description: 'Provide legal advice, represent clients in court, and draft legal documents.', job_outlook: 'Very Good', required_education: 'Law Degree (LLB) + Bar Exam', salary_range: '$1,500 - $5,000/month', skills_required: 'Legal knowledge, Communication, Analysis', universities: 'Louis Arthur Grimes School of Law, University of Liberia' },
  { title: 'Judge', category: 'Law', description: 'Preside over court cases and make legal decisions.', job_outlook: 'Good', required_education: 'Law Degree + Experience', salary_range: '$2,500 - $6,000/month', skills_required: 'Legal knowledge, Fairness, Decision-making', universities: 'Louis Arthur Grimes School of Law' },
  { title: 'Paralegal', category: 'Law', description: 'Assist lawyers with legal research and document preparation.', job_outlook: 'Very Good', required_education: 'Paralegal Certificate or Law Degree', salary_range: '$600 - $2,000/month', skills_required: 'Legal knowledge, Research, Writing', universities: 'Legal Training Programs' },
  { title: 'Legal Advisor', category: 'Law', description: 'Provide legal guidance to organizations and individuals.', job_outlook: 'Very Good', required_education: 'Law Degree', salary_range: '$1,200 - $4,000/month', skills_required: 'Legal knowledge, Communication, Analysis', universities: 'Louis Arthur Grimes School of Law' },
  { title: 'Court Reporter', category: 'Law', description: 'Record court proceedings and create transcripts.', job_outlook: 'Good', required_education: 'Court Reporting Certificate', salary_range: '$700 - $2,000/month', skills_required: 'Typing, Attention to detail, Legal knowledge', universities: 'Court Reporting Schools' },
  { title: 'Police Officer', category: 'Law', description: 'Enforce laws, maintain public safety, and investigate crimes.', job_outlook: 'Very Good', required_education: 'High School + Police Training', salary_range: '$600 - $1,800/month', skills_required: 'Law enforcement, Physical fitness, Communication', universities: 'Police Training Academy' },
  { title: 'Correctional Officer', category: 'Law', description: 'Supervise inmates in prisons and correctional facilities.', job_outlook: 'Good', required_education: 'High School + Training', salary_range: '$500 - $1,500/month', skills_required: 'Security, Communication, Patience', universities: 'Correctional Training Programs' },
  { title: 'Probation Officer', category: 'Law', description: 'Supervise offenders on probation and help with rehabilitation.', job_outlook: 'Good', required_education: 'Criminal Justice or Social Work Degree', salary_range: '$800 - $2,200/month', skills_required: 'Criminal justice, Communication, Counseling', universities: 'University of Liberia' },
  { title: 'Legal Researcher', category: 'Law', description: 'Conduct legal research to support cases and legal decisions.', job_outlook: 'Good', required_education: 'Law Degree or Legal Research Training', salary_range: '$800 - $2,500/month', skills_required: 'Research, Legal knowledge, Writing', universities: 'Louis Arthur Grimes School of Law' },
  { title: 'Mediator', category: 'Law', description: 'Help parties resolve disputes through negotiation and mediation.', job_outlook: 'Good', required_education: 'Law Degree or Mediation Training', salary_range: '$1,000 - $3,000/month', skills_required: 'Mediation, Communication, Problem-solving', universities: 'Mediation Training Programs' },

  // Arts & Media (10)
  { title: 'Journalist', category: 'Media', description: 'Research and report news stories for newspapers, TV, or online media.', job_outlook: 'Good', required_education: 'Journalism or Communications Degree', salary_range: '$600 - $2,500/month', skills_required: 'Writing, Research, Communication', universities: 'University of Liberia' },
  { title: 'Photographer', category: 'Arts', description: 'Take photos for events, portraits, or commercial purposes.', job_outlook: 'Good', required_education: 'Photography Training or Self-taught', salary_range: '$500 - $2,500/month', skills_required: 'Photography, Creativity, Technical skills', universities: 'Art Schools, Self-training' },
  { title: 'Graphic Designer', category: 'Arts', description: 'Create visual designs for websites, advertisements, and publications.', job_outlook: 'Very Good', required_education: 'Graphic Design Degree or Training', salary_range: '$800 - $3,000/month', skills_required: 'Design, Creativity, Software skills', universities: 'Art Schools, University of Liberia' },
  { title: 'Video Editor', category: 'Media', description: 'Edit video footage for TV, films, or online content.', job_outlook: 'Very Good', required_education: 'Video Production Training', salary_range: '$800 - $3,000/month', skills_required: 'Video editing, Creativity, Technical skills', universities: 'Media Training Programs' },
  { title: 'Radio Host', category: 'Media', description: 'Host radio shows and engage with listeners on air.', job_outlook: 'Good', required_education: 'Communications Degree or Training', salary_range: '$600 - $2,000/month', skills_required: 'Communication, Public speaking, Personality', universities: 'University of Liberia, Media Training' },
  { title: 'Content Creator', category: 'Media', description: 'Create content for social media, blogs, or online platforms.', job_outlook: 'Very Good', required_education: 'Communications or Self-taught', salary_range: 'Variable - Depends on platform', skills_required: 'Content creation, Creativity, Marketing', universities: 'Self-training, Online courses' },
  { title: 'Public Relations Officer', category: 'Media', description: 'Manage public image and communications for organizations.', job_outlook: 'Good', required_education: 'PR or Communications Degree', salary_range: '$800 - $2,500/month', skills_required: 'Communication, Writing, Media relations', universities: 'University of Liberia' },
  { title: 'Musician', category: 'Arts', description: 'Perform music, compose songs, or teach music.', job_outlook: 'Good', required_education: 'Music Training or Self-taught', salary_range: 'Variable', skills_required: 'Musical talent, Performance, Creativity', universities: 'Music Schools, Self-training' },
  { title: 'Writer', category: 'Arts', description: 'Write books, articles, scripts, or other written content.', job_outlook: 'Good', required_education: 'Writing Degree or Self-taught', salary_range: 'Variable', skills_required: 'Writing, Creativity, Research', universities: 'University of Liberia, Self-training' },
  { title: 'Event Photographer', category: 'Arts', description: 'Photograph weddings, parties, and special events.', job_outlook: 'Good', required_education: 'Photography Training', salary_range: '$500 - $2,000/event', skills_required: 'Photography, People skills, Reliability', universities: 'Photography Training' },

  // Social Services (10)
  { title: 'Social Worker', category: 'Social Services', description: 'Help individuals and families cope with challenges and access resources.', job_outlook: 'Very Good', required_education: 'Social Work Degree', salary_range: '$700 - $2,200/month', skills_required: 'Empathy, Communication, Problem-solving', universities: 'University of Liberia' },
  { title: 'Community Development Officer', category: 'Social Services', description: 'Work with communities to improve living conditions and opportunities.', job_outlook: 'Very Good', required_education: 'Community Development or Social Work Degree', salary_range: '$800 - $2,500/month', skills_required: 'Community work, Communication, Planning', universities: 'University of Liberia' },
  { title: 'Youth Counselor', category: 'Social Services', description: 'Provide counseling and support to young people facing challenges.', job_outlook: 'Very Good', required_education: 'Counseling or Social Work Degree', salary_range: '$700 - $2,200/month', skills_required: 'Counseling, Empathy, Communication', universities: 'University of Liberia' },
  { title: 'Child Protection Officer', category: 'Social Services', description: 'Protect children from abuse and ensure their welfare.', job_outlook: 'Very Good', required_education: 'Social Work or Child Protection Degree', salary_range: '$800 - $2,500/month', skills_required: 'Child protection, Communication, Investigation', universities: 'University of Liberia' },
  { title: 'Rehabilitation Counselor', category: 'Social Services', description: 'Help people with disabilities find employment and live independently.', job_outlook: 'Good', required_education: 'Rehabilitation Counseling Degree', salary_range: '$800 - $2,500/month', skills_required: 'Counseling, Empathy, Patience', universities: 'University of Liberia' },
  { title: 'Substance Abuse Counselor', category: 'Social Services', description: 'Help people overcome addiction and substance abuse problems.', job_outlook: 'Very Good', required_education: 'Counseling or Social Work Degree', salary_range: '$800 - $2,500/month', skills_required: 'Counseling, Empathy, Patience', universities: 'University of Liberia' },
  { title: 'Family Therapist', category: 'Social Services', description: 'Help families resolve conflicts and improve relationships.', job_outlook: 'Good', required_education: 'Family Therapy or Counseling Degree', salary_range: '$1,000 - $3,000/month', skills_required: 'Therapy, Communication, Empathy', universities: 'University of Liberia' },
  { title: 'Community Health Worker', category: 'Social Services', description: 'Provide basic health services and education in communities.', job_outlook: 'Very Good', required_education: 'Community Health Training', salary_range: '$500 - $1,500/month', skills_required: 'Health knowledge, Communication, Empathy', universities: 'Health Training Programs' },
  { title: 'Housing Officer', category: 'Social Services', description: 'Help people find housing and manage housing programs.', job_outlook: 'Good', required_education: 'Social Work or Public Administration Degree', salary_range: '$700 - $2,200/month', skills_required: 'Housing knowledge, Communication, Organization', universities: 'University of Liberia' },
  { title: 'Disability Rights Advocate', category: 'Social Services', description: 'Advocate for the rights and inclusion of people with disabilities.', job_outlook: 'Good', required_education: 'Social Work or Law Degree', salary_range: '$800 - $2,500/month', skills_required: 'Advocacy, Communication, Legal knowledge', universities: 'University of Liberia' },

  // Skilled Trades (10)
  { title: 'Electrician', category: 'Trades', description: 'Install and repair electrical systems in buildings and equipment.', job_outlook: 'Excellent', required_education: 'Electrician Apprenticeship + Certification', salary_range: '$800 - $2,500/month', skills_required: 'Electrical work, Problem-solving, Safety', universities: 'Technical Training Institutes' },
  { title: 'Plumber', category: 'Trades', description: 'Install and repair plumbing systems in buildings.', job_outlook: 'Excellent', required_education: 'Plumbing Apprenticeship + Certification', salary_range: '$700 - $2,200/month', skills_required: 'Plumbing, Problem-solving, Physical work', universities: 'Technical Training Institutes' },
  { title: 'Carpenter', category: 'Trades', description: 'Build and repair structures made of wood.', job_outlook: 'Excellent', required_education: 'Carpentry Apprenticeship + Training', salary_range: '$600 - $2,000/month', skills_required: 'Carpentry, Math, Physical work', universities: 'Vocational Training Institutes' },
  { title: 'Mason', category: 'Trades', description: 'Build structures using bricks, stones, or concrete blocks.', job_outlook: 'Very Good', required_education: 'Masonry Apprenticeship + Training', salary_range: '$600 - $2,000/month', skills_required: 'Masonry, Physical work, Attention to detail', universities: 'Vocational Training Institutes' },
  { title: 'Welder', category: 'Trades', description: 'Join metal parts using welding techniques.', job_outlook: 'Very Good', required_education: 'Welding Training + Certification', salary_range: '$700 - $2,500/month', skills_required: 'Welding, Technical skills, Safety', universities: 'Technical Training Institutes' },
  { title: 'Mechanic', category: 'Trades', description: 'Repair and maintain vehicles and machinery.', job_outlook: 'Excellent', required_education: 'Mechanics Training + Experience', salary_range: '$700 - $2,500/month', skills_required: 'Mechanical skills, Problem-solving, Technical knowledge', universities: 'Technical Training Institutes' },
  { title: 'Tailor', category: 'Trades', description: 'Make and alter clothing and textiles.', job_outlook: 'Very Good', required_education: 'Tailoring Training', salary_range: '$500 - $1,800/month', skills_required: 'Sewing, Creativity, Attention to detail', universities: 'Vocational Training Institutes' },
  { title: 'Hairdresser', category: 'Trades', description: 'Cut, style, and color hair for clients.', job_outlook: 'Very Good', required_education: 'Cosmetology Training + License', salary_range: '$500 - $2,000/month', skills_required: 'Hair styling, Creativity, Customer service', universities: 'Beauty Schools' },
  { title: 'Chef', category: 'Trades', description: 'Prepare and cook food in restaurants or catering services.', job_outlook: 'Very Good', required_education: 'Culinary Training or Experience', salary_range: '$600 - $2,500/month', skills_required: 'Cooking, Creativity, Time management', universities: 'Culinary Schools' },
  { title: 'Construction Manager', category: 'Trades', description: 'Oversee construction projects from planning to completion.', job_outlook: 'Very Good', required_education: 'Construction Management Degree or Experience', salary_range: '$1,200 - $3,500/month', skills_required: 'Construction, Management, Planning', universities: 'University of Liberia' },

  // Additional Careers (10)
  { title: 'Architect', category: 'Engineering', description: 'Design buildings and oversee construction projects.', job_outlook: 'Very Good', required_education: 'Architecture Degree', salary_range: '$1,500 - $4,500/month', skills_required: 'Design, Engineering, Creativity', universities: 'University of Liberia' },
  { title: 'Surveyor', category: 'Engineering', description: 'Measure and map land for construction and development projects.', job_outlook: 'Good', required_education: 'Surveying Degree or Training', salary_range: '$1,000 - $3,000/month', skills_required: 'Surveying, Math, Technical skills', universities: 'University of Liberia' },
  { title: 'Urban Planner', category: 'Engineering', description: 'Plan and design cities and communities for sustainable development.', job_outlook: 'Good', required_education: 'Urban Planning Degree', salary_range: '$1,200 - $3,500/month', skills_required: 'Planning, Design, Environmental knowledge', universities: 'University of Liberia' },
  { title: 'Pilot', category: 'Transportation', description: 'Fly aircraft for commercial airlines or private companies.', job_outlook: 'Good', required_education: 'Pilot License + Training', salary_range: '$2,000 - $8,000/month', skills_required: 'Flying, Technical skills, Decision-making', universities: 'Flight Schools' },
  { title: 'Marine Engineer', category: 'Engineering', description: 'Design and maintain ships and marine equipment.', job_outlook: 'Good', required_education: 'Marine Engineering Degree', salary_range: '$1,500 - $4,500/month', skills_required: 'Engineering, Marine knowledge, Problem-solving', universities: 'University of Liberia' },
  { title: 'Translator', category: 'Language', description: 'Translate written or spoken content between languages.', job_outlook: 'Good', required_education: 'Language Degree or Fluency', salary_range: '$800 - $2,500/month', skills_required: 'Language skills, Writing, Cultural knowledge', universities: 'University of Liberia' },
  { title: 'Interpreter', category: 'Language', description: 'Provide real-time translation during meetings or events.', job_outlook: 'Good', required_education: 'Language Fluency + Training', salary_range: '$600 - $2,000/month', skills_required: 'Language skills, Quick thinking, Communication', universities: 'Language Training Programs' },
  { title: 'Tour Guide', category: 'Tourism', description: 'Lead tourists on tours and share information about local attractions.', job_outlook: 'Good', required_education: 'Tourism Training or Knowledge', salary_range: '$500 - $1,500/month', skills_required: 'Communication, Local knowledge, People skills', universities: 'Tourism Training Programs' },
  { title: 'Hotel Manager', category: 'Tourism', description: 'Manage hotel operations and ensure guest satisfaction.', job_outlook: 'Good', required_education: 'Hospitality Management Degree', salary_range: '$1,000 - $3,000/month', skills_required: 'Management, Customer service, Organization', universities: 'University of Liberia' },
  { title: 'Sports Coach', category: 'Sports', description: 'Train athletes and teams to improve performance.', job_outlook: 'Good', required_education: 'Sports Science or Coaching Training', salary_range: '$600 - $2,000/month', skills_required: 'Sports knowledge, Leadership, Communication', universities: 'Sports Training Programs' }
];

// Function to add careers to database
function addCareers() {
  console.log('Starting to add careers to database...');
  
  const insertCareer = db.prepare(`
    INSERT INTO careers (title, description, job_outlook, required_education, salary_range, skills_required, universities, category)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?)
  `);

  const insertMany = db.transaction((careers) => {
    let added = 0;
    let skipped = 0;
    
    for (const career of careers) {
      try {
        // Check if career already exists
        const existing = db.prepare('SELECT id FROM careers WHERE title = ?').get(career.title);
        if (existing) {
          skipped++;
          continue;
        }
        
        insertCareer.run(
          career.title,
          career.description,
          career.job_outlook,
          career.required_education,
          career.salary_range,
          career.skills_required,
          career.universities,
          career.category
        );
        added++;
      } catch (error) {
        console.error(`Error adding career "${career.title}":`, error.message);
      }
    }
    
    return { added, skipped };
  });

  const result = insertMany(careers);
  console.log(`✅ Successfully added ${result.added} careers`);
  console.log(`⏭️  Skipped ${result.skipped} careers (already exist)`);
  console.log(`📊 Total careers in database: ${db.prepare('SELECT COUNT(*) as count FROM careers').get().count}`);
}

// Run the script
addCareers();

